cleanPrometheusOperatorObjectNames: true
fullnameOverride: monitoring

crds:
  enabled: true

defaultRules:
  create: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.k8s.maresdemo.com
    paths:
      - /
    pathType: Prefix
    tls:
      - hosts:
          - prometheus.k8s.maresdemo.com
        secretName: prometheus-ingress-tls

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    replicas: 2

    retention: 2d
    retentionSize: 40GiB

    podDisruptionBudget:
      enabled: true
      minAvailable: 1

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
